import Footer from "@/components/footer";
import "./globals.css";
import Navbar from "@/components/navbar";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <main className=" flex flex-col h-screen justify-between ">
          <Navbar/>
          <saction className=" mb-auto">{children}</saction>
          <Footer/>
        </main>
      </body>
    </html>
  );
}
